# fly.toml app configuration file generated for luvdb on 2023-06-15T18:00:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "luvdb"
primary_region = "ams"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 75

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[services]]
  [services.concurrency]
      hard_limit = 100
      soft_limit = 75
      type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true 