# fly.toml app configuration file generated for luvdb on 2023-06-14T11:35:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "luvdb"
primary_region = "ams"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DATABASE_PATH = "/code/db.sqlite3"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
